query accountMetrics($toRate: Boolean, $perSecond: Boolean, $withMissingData: Boolean, $buckets: Int, $labels: [TimeseriesMetricType!], $types: [String!], $toRate1: Boolean, $perSecond1: Boolean, $withMissingData1: Boolean, $perSecond2: Boolean, $withMissingData2: Boolean, $perSecond3: Boolean, $withMissingData3: Boolean, $siteIDs: [ID!], $ids: [String!], $toRate2: Boolean, $perSecond4: Boolean, $withMissingData4: Boolean, $perSecond5: Boolean, $withMissingData5: Boolean, $perSecond6: Boolean, $withMissingData6: Boolean, $userIDs: [ID!], $perSecond7: Boolean, $withMissingData7: Boolean, $labels1: [TimeseriesMetricType!], $buckets1: Int, $accountID: ID, $id: ID, $timeFrame: TimeFrame!, $groupInterfaces: Boolean, $groupDevices: Boolean){
    accountMetrics(accountID: $accountID, id: $id, timeFrame: $timeFrame, groupInterfaces: $groupInterfaces, groupDevices: $groupDevices){
        id
        from
        to
        granularity
        sites(siteIDs: $siteIDs, ids: $ids){
            id
            interfaces{
                metrics(toRate: $toRate){
                    duration
                    granularity
                    bytesDownstream
                    bytesUpstream
                    bytesTotal
                    lostDownstream
                    lostDownstreamPcnt
                    lostUpstream
                    lostUpstreamPcnt
                    packetsDownstream
                    packetsUpstream
                    jitterUpstream
                    jitterDownstream
                    packetsDiscardedDownstream
                    packetsDiscardedUpstream
                    rtt
                    hostCount
                    hostLimit
                    flowCount
                }
                name
                timeseries(buckets: $buckets, labels: $labels){
                    data(perSecond: $perSecond, withMissingData: $withMissingData)
                    label
                    dimensions{
                        label
                        value
                    }
                    key{
                        measureFieldName
                        dimensions{
                            fieldName
                            value
                        }
                    }
                    sum
                    units
                    info
                }
                annotations(types: $types){
                    time
                    label
                    shortLabel
                    type
                }
                periods{
                    duration
                    title
                    type
                }
                remoteIPInfo{
                    ip
                    countryCode
                    countryName
                    city
                    state
                    provider
                    latitude
                    longitude
                }
                remoteIP
                socketInfo{
                    id
                    serial
                    isPrimary
                    platform
                    version
                    versionUpdateTime
                }
                ipsecInfo{
                    isPrimary
                    catoIP
                    remoteIP
                    ikeVersion
                }
                interfaceInfo{
                    id
                    name
                    upstreamBandwidth
                    downstreamBandwidth
                    destType
                }
            }
            metrics(toRate: $toRate1){
                duration
                granularity
                bytesDownstream
                bytesUpstream
                bytesTotal
                lostDownstream
                lostDownstreamPcnt
                lostUpstream
                lostUpstreamPcnt
                packetsDownstream
                packetsUpstream
                jitterUpstream
                jitterDownstream
                packetsDiscardedDownstream
                packetsDiscardedUpstream
                rtt
                hostCount
                hostLimit
                flowCount
            }
            name
            info{
                name
                type
                description
                countryCode
                region
                countryName
                isHA
                connType
                creationTime
                interfaces{
                    id
                    name
                    upstreamBandwidth
                    downstreamBandwidth
                    destType
                }
                sockets{
                    id
                    serial
                    isPrimary
                    platform
                    version
                    versionUpdateTime
                }
                ipsec{
                    isPrimary
                    catoIP
                    remoteIP
                    ikeVersion
                }
            }
            hostCount{
                data(perSecond: $perSecond1, withMissingData: $withMissingData1)
                label
                dimensions{
                    label
                    value
                }
                key{
                    measureFieldName
                }
                sum
                units
                info
            }
            flowCount{
                data(perSecond: $perSecond2, withMissingData: $withMissingData2)
                label
                dimensions{
                    label
                    value
                }
                key{
                    measureFieldName
                }
                sum
                units
                info
            }
            hostLimit{
                data(perSecond: $perSecond3, withMissingData: $withMissingData3)
                label
                dimensions{
                    label
                    value
                }
                key{
                    measureFieldName
                }
                sum
                units
                info
            }
        }
        users(userIDs: $userIDs){
            id
            interfaces{
                name
                remoteIP
            }
            metrics(toRate: $toRate2){
                duration
                granularity
                bytesDownstream
                bytesUpstream
                bytesTotal
                lostDownstream
                lostDownstreamPcnt
                lostUpstream
                lostUpstreamPcnt
                packetsDownstream
                packetsUpstream
                jitterUpstream
                jitterDownstream
                packetsDiscardedDownstream
                packetsDiscardedUpstream
                rtt
                hostCount
                hostLimit
                flowCount
            }
            name
            info{
                name
                type
                description
                countryCode
                region
                countryName
                isHA
                connType
                creationTime
            }
            hostCount{
                data(perSecond: $perSecond4, withMissingData: $withMissingData4)
                label
                sum
                units
                info
            }
            flowCount{
                data(perSecond: $perSecond5, withMissingData: $withMissingData5)
                label
                sum
                units
                info
            }
            hostLimit{
                data(perSecond: $perSecond6, withMissingData: $withMissingData6)
                label
                sum
                units
                info
            }
        }
        timeseries(labels: $labels1, buckets: $buckets1){
            data(perSecond: $perSecond7, withMissingData: $withMissingData7)
            label
            sum
            units
            info
        }
    }
}