query accountSnapshot($siteIDs: [ID!], $ids: [Int!], $userIDs: [ID!], $ids1: [Int!], $accountID: ID, $id: ID){
    accountSnapshot(accountID: $accountID, id: $id){
        id
        sites(siteIDs: $siteIDs, ids: $ids){
            id
            protoId
            connectivityStatus
            haStatus{
                readiness
                wanConnectivity
                keepalive
                socketVersion
            }
            operationalStatus
            lastConnected
            connectedSince
            popName
            devices{
                id
                name
                identifier
                connected
                haRole
                interfaces{
                    connected
                    id
                    name
                    physicalPort
                    naturalOrder
                    popName
                    previousPopID
                    previousPopName
                    tunnelConnectionReason
                    tunnelUptime
                    tunnelRemoteIP
                    tunnelRemoteIPInfo{
                        ip
                        countryCode
                        countryName
                        city
                        state
                        provider
                        latitude
                        longitude
                    }
                    info{
                        id
                        name
                        upstreamBandwidth
                        downstreamBandwidth
                        destType
                    }
                    cellularInterfaceInfo{
                        networkType
                        simSlotId
                        modemStatus
                        isModemConnected
                        iccid
                        imei
                        operatorName
                        isModemSuspended
                        apn
                        apnSelectionMethod
                        signalStrength
                        isRoamingAllowed
                        simNumber
                        disconnectionReason
                        isSimSlot1Detected
                        isSimSlot2Detected
                    }
                }
                lastConnected
                lastDuration
                connectedSince
                lastPopID
                lastPopName
                recentConnections{
                    duration
                    interfaceName
                    deviceName
                    lastConnected
                    popName
                    remoteIP
                    remoteIPInfo{
                        ip
                        countryCode
                        countryName
                        city
                        state
                        provider
                        latitude
                        longitude
                    }
                }
                type
                socketInfo{
                    id
                    serial
                    isPrimary
                    platform
                    version
                    versionUpdateTime
                }
                interfacesLinkState{
                    id
                    up
                    mediaIn
                    linkSpeed
                    duplex
                }
                osType
                osVersion
                version
                versionNumber
                releaseGroup
                mfaExpirationTime
                mfaCreationTime
                internalIP
            }
            info{
                name
                type
                description
                countryCode
                region
                countryName
                isHA
                connType
                creationTime
                interfaces{
                    id
                    name
                    upstreamBandwidth
                    downstreamBandwidth
                    destType
                }
                sockets{
                    id
                    serial
                    isPrimary
                    platform
                    version
                    versionUpdateTime
                }
                ipsec{
                    isPrimary
                    catoIP
                    remoteIP
                    ikeVersion
                }
            }
            hostCount
            altWanStatus
        }
        users(userIDs: $userIDs, ids: $ids1){
            id
            connectivityStatus
            operationalStatus
            name
            deviceName
            uptime
            lastConnected
            version
            versionNumber
            popID
            popName
            remoteIP
            remoteIPInfo{
                ip
                countryCode
                countryName
                city
                state
                provider
                latitude
                longitude
            }
            internalIP
            osType
            osVersion
            devices{
                id
                name
                identifier
                connected
                haRole
                lastConnected
                lastDuration
                connectedSince
                lastPopID
                lastPopName
                type
                osType
                osVersion
                version
                versionNumber
                releaseGroup
                mfaExpirationTime
                mfaCreationTime
                internalIP
            }
            connectedInOffice
            info{
                name
                status
                email
                creationTime
                phoneNumber
                origin
                authMethod
            }
            recentConnections{
                duration
                interfaceName
                deviceName
                lastConnected
                popName
                remoteIP
            }
        }
        timestamp
    }
}