mutation adminUpdateAdmin ( $adminID:ID! $updateAdminInput:UpdateAdminInput! $accountId:ID! ) {
	admin ( accountId:$accountId  ) {
		updateAdmin ( adminID:$adminID  input:$updateAdminInput  )  {
			adminID
		}

	}	
}
