query admins($accountID: ID!, $limit: Int, $from: Int, $search: String, $sort: [SortInput], $adminIDs: [ID!]){
    admins(accountID: $accountID, limit: $limit, from: $from, search: $search, sort: $sort, adminIDs: $adminIDs){
        items{
            id
            version
            role
            firstName
            lastName
            email
            creationDate
            modifyDate
            status
            passwordNeverExpires
            mfaEnabled
            nativeAccountID
            allowedItems{
                id
                name
                type
            }
            presentUsageAndEvents
            managedRoles{
                role{
                    id
                    name
                    description
                    isPredefined
                }
                allowedEntities{
                    id
                    name
                    type
                }
                allowedAccounts
            }
            resellerRoles{
                role{
                    id
                    name
                    description
                    isPredefined
                }
                allowedEntities{
                    id
                    name
                    type
                }
                allowedAccounts
            }
        }
        total
    }
}