query appStatsTimeSeries($perSecond: Boolean, $withMissingData: Boolean, $buckets: Int!, $accountID: ID!, $timeFrame: TimeFrame!, $measures: [Measure], $dimensions: [Dimension], $filters: [AppStatsFilter!]){
    appStatsTimeSeries(accountID: $accountID, timeFrame: $timeFrame, measures: $measures, dimensions: $dimensions, filters: $filters){
        id
        from
        to
        granularity
        timeseries(buckets: $buckets){
            data(perSecond: $perSecond, withMissingData: $withMissingData)
            label
            dimensions{
                label
                value
            }
            key{
                measureFieldName
                dimensions{
                    fieldName
                    value
                }
            }
            sum
            units
            info
        }
    }
}