mutation policyInternetFirewallMoveSection ( $internetFirewallPolicyMutationInput:InternetFirewallPolicyMutationInput $policyMoveSectionInput:PolicyMoveSectionInput! $accountId:ID! ) {
	policy ( accountId:$accountId  ) {
		internetFirewall ( input:$internetFirewallPolicyMutationInput  )  {
			moveSection ( input:$policyMoveSectionInput   ) {
				section  {
					audit {
						updatedTime 
						updatedBy 
					}
					section {
						id 
						name 
					}
					properties
				}

				status 
				errors  {
					errorMessage
					errorCode
				}

			}
		}

	}	
}
