mutation policyWanFirewallDiscardPolicyRevision ( $policyDiscardRevisionInput:PolicyDiscardRevisionInput $accountId:ID! ) {
	policy ( accountId:$accountId  ) {
		wanFirewall  {
			discardPolicyRevision ( input:$policyDiscardRevisionInput   ) {
				policy  {
					enabled
					rules {
						audit  {
							updatedTime
							updatedBy
						}

						rule  {
							id
							name
							description
							index
							section {
								id 
								name 
							}
							enabled
							source {
								host  {
									id
									name
								}

								site  {
									id
									name
								}

								subnet 
								ip 
								ipRange  {
									from
									to
								}

								globalIpRange  {
									id
									name
								}

								networkInterface  {
									id
									name
								}

								siteNetworkSubnet  {
									id
									name
								}

								floatingSubnet  {
									id
									name
								}

								user  {
									id
									name
								}

								usersGroup  {
									id
									name
								}

								group  {
									id
									name
								}

								systemGroup  {
									id
									name
								}

							}
							connectionOrigin
							country {
								id 
								name 
							}
							device {
								id 
								name 
							}
							deviceOS
							destination {
								host  {
									id
									name
								}

								site  {
									id
									name
								}

								subnet 
								ip 
								ipRange  {
									from
									to
								}

								globalIpRange  {
									id
									name
								}

								networkInterface  {
									id
									name
								}

								siteNetworkSubnet  {
									id
									name
								}

								floatingSubnet  {
									id
									name
								}

								user  {
									id
									name
								}

								usersGroup  {
									id
									name
								}

								group  {
									id
									name
								}

								systemGroup  {
									id
									name
								}

							}
							application {
								application  {
									id
									name
								}

								appCategory  {
									id
									name
								}

								customApp  {
									id
									name
								}

								customCategory  {
									id
									name
								}

								sanctionedAppsCategory  {
									id
									name
								}

								domain 
								fqdn 
								ip 
								subnet 
								ipRange  {
									from
									to
								}

								globalIpRange  {
									id
									name
								}

							}
							service {
								standard  {
									id
									name
								}

								custom  {
									port
									portRangeCustomService: portRange {
										from 
										to 
									}
									protocol
								}

							}
							action
							tracking {
								event  {
									enabled
								}

								alert  {
									enabled
									frequency
									subscriptionGroup {
										id 
										name 
									}
									webhook {
										id 
										name 
									}
									mailingList {
										id 
										name 
									}
								}

							}
							schedule {
								activeOn 
								customTimeframe  {
									from
									to
								}

								customRecurring  {
									from
									to
									days
								}

							}
							direction
							exceptions {
								name 
								source  {
									host {
										id 
										name 
									}
									site {
										id 
										name 
									}
									subnet
									ip
									ipRange {
										from 
										to 
									}
									globalIpRange {
										id 
										name 
									}
									networkInterface {
										id 
										name 
									}
									siteNetworkSubnet {
										id 
										name 
									}
									floatingSubnet {
										id 
										name 
									}
									user {
										id 
										name 
									}
									usersGroup {
										id 
										name 
									}
									group {
										id 
										name 
									}
									systemGroup {
										id 
										name 
									}
								}

								deviceOS 
								destination  {
									host {
										id 
										name 
									}
									site {
										id 
										name 
									}
									subnet
									ip
									ipRange {
										from 
										to 
									}
									globalIpRange {
										id 
										name 
									}
									networkInterface {
										id 
										name 
									}
									siteNetworkSubnet {
										id 
										name 
									}
									floatingSubnet {
										id 
										name 
									}
									user {
										id 
										name 
									}
									usersGroup {
										id 
										name 
									}
									group {
										id 
										name 
									}
									systemGroup {
										id 
										name 
									}
								}

								country  {
									id
									name
								}

								device  {
									id
									name
								}

								application  {
									application {
										id 
										name 
									}
									appCategory {
										id 
										name 
									}
									customApp {
										id 
										name 
									}
									customCategory {
										id 
										name 
									}
									sanctionedAppsCategory {
										id 
										name 
									}
									domain
									fqdn
									ip
									subnet
									ipRange {
										from 
										to 
									}
									globalIpRange {
										id 
										name 
									}
								}

								service  {
									standard {
										id 
										name 
									}
									custom {
										port 
										portRange  {
											from
											to
										}

										protocol 
									}
								}

								connectionOrigin 
								direction 
							}
						}

						properties 
					}
					sections {
						audit  {
							updatedTime
							updatedBy
						}

						section  {
							id
							name
						}

						properties 
					}
					auditWanFirewallPolicy: audit {
						publishedTime 
						publishedBy 
					}
					revisionWanFirewallPolicy: revision {
						id 
						name 
						description 
						changes 
						createdTime 
						updatedTime 
					}
				}

				status 
				errors  {
					errorMessage
					errorCode
				}

			}
		}

	}	
}
