mutation siteUpdateNetworkRange ( $networkRangeId:ID! $updateNetworkRangeInput:UpdateNetworkRangeInput! $accountId:ID! ) {
	site ( accountId:$accountId  ) {
		updateNetworkRange ( networkRangeId:$networkRangeId  input:$updateNetworkRangeInput  )  {
			networkRangeId
		}

	}	
}
