mutation siteAddIpsecIkeV2SiteTunnels ( $siteId:ID! $addIpsecIkeV2SiteTunnelsInput:AddIpsecIkeV2SiteTunnelsInput! $accountId:ID! ) {
	site ( accountId:$accountId  ) {
		addIpsecIkeV2SiteTunnels ( siteId:$siteId  input:$addIpsecIkeV2SiteTunnelsInput  )  {
			siteId
			primaryAddIpsecIkeV2SiteTunnelsPayload: primary {
				fqdn 
				tunnels  {
					tunnelIdAddIpsecIkeV2SiteTunnelPayload: tunnelId
					localId
				}

			}
			secondaryAddIpsecIkeV2SiteTunnelsPayload: secondary {
				fqdn 
				tunnels  {
					tunnelIdAddIpsecIkeV2SiteTunnelPayload: tunnelId
					localId
				}

			}
		}

	}	
}
