mutation siteUpdateSocketInterface ( $siteId:ID! $socketInterfaceId:SocketInterfaceIDEnum! $updateSocketInterfaceInput:UpdateSocketInterfaceInput! $accountId:ID! ) {
	site ( accountId:$accountId  ) {
		updateSocketInterface ( siteId:$siteId  socketInterfaceId:$socketInterfaceId  input:$updateSocketInterfaceInput  )  {
			siteId
			socketInterfaceId
		}

	}	
}
