mutation siteAddStaticHost ( $siteId:ID! $addStaticHostInput:AddStaticHostInput! $accountId:ID! ) {
	site ( accountId:$accountId  ) {
		addStaticHost ( siteId:$siteId  input:$addStaticHostInput  )  {
			hostId
		}

	}	
}
