mutation siteUpdateStaticHost ( $hostId:ID! $updateStaticHostInput:UpdateStaticHostInput! $accountId:ID! ) {
	site ( accountId:$accountId  ) {
		updateStaticHost ( hostId:$hostId  input:$updateStaticHostInput  )  {
			hostId
		}

	}	
}
