mutation siteUpdateSiteGeneralDetails ( $siteId:ID! $updateSiteGeneralDetailsInput:UpdateSiteGeneralDetailsInput! $accountId:ID! ) {
	site ( accountId:$accountId  ) {
		updateSiteGeneralDetails ( siteId:$siteId  input:$updateSiteGeneralDetailsInput  )  {
			siteId
		}

	}	
}
