query subDomains($accountID: ID!, $managedAccount: Boolean){
    subDomains(accountID: $accountID, managedAccount: $managedAccount){
        accountId
        accountName
        accountType
        subDomain
    }
}