query xdr($input: StoryInput!, $storyId: ID, $producer: StoryProducerEnum, $incidentId: ID, $accountID: ID!){
    xdr(accountID: $accountID){
        stories(input: $input){
            paging{
                from
                limit
                total
            }
            items{
                id
                accountId
                analystName
                analystEmail
                accountName
                updatedAt
                createdAt
                playbook
                summary
                incident{
                    id
                    firstSignal
                    lastSignal
                    engineType
                    vendor
                    producer
                    producerName
                    connectionType
                    indication
                    queryName
                    criticality
                    source
                    ticket
                    status
                    research
                    siteName
                    storyDuration
                    description
                    sourceIp
                    analystFeedback{
                        verdict
                        severity
                        threatType{
                            name
                            recommendedAction
                            details
                        }
                        threatClassification
                        additionalInfo
                    }
                    site{
                        id
                        name
                    }
                    user{
                        id
                        name
                    }
                    predictedVerdict
                    predictedThreatType
                }
                timeline{
                    createdAt
                    description
                    context
                    type
                    descriptions
                    category
                    additionalInfo
                    analystInfo{
                        name
                        email
                    }
                }
            }
        }
        story(storyId: $storyId, producer: $producer, incidentId: $incidentId){
            id
            accountId
            analystName
            analystEmail
            accountName
            updatedAt
            createdAt
            playbook
            summary
            incident{
                id
                firstSignal
                lastSignal
                engineType
                vendor
                producer
                producerName
                connectionType
                indication
                queryName
                criticality
                source
                ticket
                status
                research
                siteName
                storyDuration
                description
                sourceIp
                predictedVerdict
                predictedThreatType
            }
            timeline{
                createdAt
                description
                context
                type
                descriptions
                category
                additionalInfo
            }
        }
    }
}